### ISSUE TITLE
Multi assets suport or i18n?

### ISSUE THREAD

**Issue by jeferson0993** [piotr-iohk/ikar#51]
🤔  Now that cardano are multi asset, are you considering adding support for other assets?
And what about internationalization ass well? 🌎 

ps: great work. 👍🏾

**Comment by piotr-iohk** [comment]
@jeferson0993 thank you for the comment :heart: 

Cardano multi-assets are supported currently. Generally everything what is supported by [cardano-wallet](https://github.com/input-output-hk/cardano-wallet) is supported by ikar as well.

Currently I have no immediate plans for adding i18n. This was/is mainly intended as a testing tool for cardano-wallet. Incidentally it may be useful as a thin UI over cardano-wallet.

**Comment by jeferson0993** [comment]
ok. Good to know. ✌🏾 .
keep improving 🔥
